version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: src/Ambev.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - postgres
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ambev;Username=postgres;Password=postgres
      - Redis__ConnectionString=redis:6379
    networks:
      - ambev-network

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ambev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ambev-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ambev-network

volumes:
  postgres-data:
  redis-data:

networks:
  ambev-network:
    driver: bridge
